services:
    phpbb.ads.location.manager:
        class: phpbb\ads\location\manager
        arguments:
            - '@phpbb.ads.location.type_collection'

# ----- Template locations -----
    phpbb.ads.location.type_collection:
        class: phpbb\di\service_collection
        arguments:
            - '@service_container'
        tags:
            - { name: service_collection, tag: phpbb.ads.location.type }

    phpbb.ads.location.type.above_footer:
        class: phpbb\ads\location\type\above_footer
        arguments:
            - '@user'
            - '@language'
        tags:
            - { name: phpbb.ads.location.type }

    phpbb.ads.location.type.above_header:
        class: phpbb\ads\location\type\above_header
        arguments:
            - '@user'
            - '@language'
        tags:
            - { name: phpbb.ads.location.type }

    phpbb.ads.location.type.after_first_post:
        class: phpbb\ads\location\type\after_first_post
        arguments:
            - '@user'
            - '@language'
        tags:
            - { name: phpbb.ads.location.type }

    phpbb.ads.location.type.after_not_first_post:
        class: phpbb\ads\location\type\after_not_first_post
        arguments:
            - '@user'
            - '@language'
        tags:
            - { name: phpbb.ads.location.type }

    phpbb.ads.location.type.after_posts:
        class: phpbb\ads\location\type\after_posts
        arguments:
            - '@user'
            - '@language'
        tags:
            - { name: phpbb.ads.location.type }

    phpbb.ads.location.type.after_profile:
        class: phpbb\ads\location\type\after_profile
        arguments:
            - '@user'
            - '@language'
        tags:
            - { name: phpbb.ads.location.type }

    phpbb.ads.location.type.before_posts:
        class: phpbb\ads\location\type\before_posts
        arguments:
            - '@user'
            - '@language'
        tags:
            - { name: phpbb.ads.location.type }

    phpbb.ads.location.type.before_profile:
        class: phpbb\ads\location\type\before_profile
        arguments:
            - '@user'
            - '@language'
        tags:
            - { name: phpbb.ads.location.type }

    phpbb.ads.location.type.below_footer:
        class: phpbb\ads\location\type\below_footer
        arguments:
            - '@user'
            - '@language'
        tags:
            - { name: phpbb.ads.location.type }

    phpbb.ads.location.type.below_header:
        class: phpbb\ads\location\type\below_header
        arguments:
            - '@user'
            - '@language'
        tags:
            - { name: phpbb.ads.location.type }
