services:
    phpbb.admanagement.location.manager:
        class: phpbb\admanagement\location\manager
        arguments:
            - '@phpbb.admanagement.location.type_collection'

# ----- Template locations -----
    phpbb.admanagement.location.type_collection:
        class: phpbb\di\service_collection
        arguments:
            - '@service_container'
        tags:
            - { name: service_collection, tag: phpbb.admanagement.location.type }

    phpbb.admanagement.location.type.above_footer:
        class: phpbb\admanagement\location\type\above_footer
        arguments:
            - '@user'
        tags:
            - { name: phpbb.admanagement.location.type }

    phpbb.admanagement.location.type.above_header:
        class: phpbb\admanagement\location\type\above_header
        arguments:
            - '@user'
        tags:
            - { name: phpbb.admanagement.location.type }

    phpbb.admanagement.location.type.after_first_post:
        class: phpbb\admanagement\location\type\after_first_post
        arguments:
            - '@user'
        tags:
            - { name: phpbb.admanagement.location.type }

    phpbb.admanagement.location.type.after_not_first_post:
        class: phpbb\admanagement\location\type\after_not_first_post
        arguments:
            - '@user'
        tags:
            - { name: phpbb.admanagement.location.type }

    phpbb.admanagement.location.type.after_posts:
        class: phpbb\admanagement\location\type\after_posts
        arguments:
            - '@user'
        tags:
            - { name: phpbb.admanagement.location.type }

    phpbb.admanagement.location.type.after_profile:
        class: phpbb\admanagement\location\type\after_profile
        arguments:
            - '@user'
        tags:
            - { name: phpbb.admanagement.location.type }

    phpbb.admanagement.location.type.before_posts:
        class: phpbb\admanagement\location\type\before_posts
        arguments:
            - '@user'
        tags:
            - { name: phpbb.admanagement.location.type }

    phpbb.admanagement.location.type.before_profile:
        class: phpbb\admanagement\location\type\before_profile
        arguments:
            - '@user'
        tags:
            - { name: phpbb.admanagement.location.type }

    phpbb.admanagement.location.type.below_footer:
        class: phpbb\admanagement\location\type\below_footer
        arguments:
            - '@user'
        tags:
            - { name: phpbb.admanagement.location.type }

    phpbb.admanagement.location.type.below_header:
        class: phpbb\admanagement\location\type\below_header
        arguments:
            - '@user'
        tags:
            - { name: phpbb.admanagement.location.type }
