phpbb_ads_click:
    path: /adsclick/{ad_id}
    defaults: { _controller: phpbb.ads.increment.controller:handle, mode: 'clicks' }
    requirements:
        mode: 'clicks'
        ad_id: '\d+'

phpbb_ads_view:
    path: /adsview/{ad_ids}
    defaults: { _controller: phpbb.ads.increment.controller:handle, mode: 'views' }
    requirements:
        mode: 'views'
        ad_ids: '(\d+-)*\d+'
