phpbb_ads_click:
    path: /adsclick/{ad_id}
    defaults: { _controller: phpbb.ads.click.controller:increment_clicks }
    requirements:
        id: '\d+'

phpbb_ads_view:
    path: /adsview
    defaults: { _controller: phpbb.ads.view.controller:increment_views }
