imports:
    - { resource: tables.yml }
    - { resource: location.yml }

services:
    phpbb.admanagement.ad.manager:
        class: phpbb\admanagement\ad\manager
        arguments:
            - '@dbal.conn'
            - '%phpbb.admanagement.tables.ads%'
            - '%phpbb.admanagement.tables.ad_locations%'

    phpbb.admanagement.admin.controller:
        class: phpbb\admanagement\controller\admin_controller
        arguments:
            - '@template'
            - '@user'
            - '@request'
            - '@phpbb.admanagement.ad.manager'
            - '@phpbb.admanagement.location.manager'
            - '@log'
            - '@config'
            - '@dbal.conn'
            - '%core.php_ext%'
            - '%core.root_path%ext/phpbb/admanagement/'
            - '%tables.groups%'

    phpbb.admanagement.listener:
        class: phpbb\admanagement\event\main_listener
        arguments:
            - '@template'
            - '@phpbb.admanagement.ad.manager'
            - '@phpbb.admanagement.location.manager'
        tags:
            - { name: event.listener }
