imports:
    - { resource: tables.yml }
    - { resource: location.yml }

services:
    phpbb.ads.ad.manager:
        class: phpbb\ads\ad\manager
        arguments:
            - '@dbal.conn'
            - '%phpbb.ads.tables.ads%'
            - '%phpbb.ads.tables.ad_locations%'

    phpbb.ads.admin.controller:
        class: phpbb\ads\controller\admin_controller
        arguments:
            - '@template'
            - '@user'
            - '@request'
            - '@phpbb.ads.ad.manager'
            - '@phpbb.ads.location.manager'
            - '@log'
            - '@config_text'
            - '@config'
            - '%core.php_ext%'
            - '%core.root_path%ext/phpbb/ads/'

    phpbb.ads.listener:
        class: phpbb\ads\event\main_listener
        arguments:
            - '@template'
            - '@user'
            - '@config_text'
            - '@config'
            - '@phpbb.ads.ad.manager'
            - '@phpbb.ads.location.manager'
        tags:
            - { name: event.listener }
